// Suomenkielisten pelimuoto-oppaiden sisältö. Pelinimet ja sääntölogiikka
// seuraavat sovelluksen fi-katalogia. Kaikki sivut syntyvät yhdestä
// pagination-mallista, joten seuraava kieli ei vaadi 21 kopioitua mallia.
//
// Julkaisuportti on silti _data/routes.js:n publishedLocales. Sisältö on
// valmisteltu teknisesti, mutta vaatii suomea äidinkielenään puhuvan golfarin
// tarkistuksen ennen kuin `fi` saa lisätä PUBLISHED-listoihin.
const guides = [
  {
    key: "matchspel", slug: "reikapeli", format: "Reikäpeli", category: "Klassikot",
    players: "2 pelaajaa", order: 1,
    lede: "Kahden pelaajan reikäkohtainen kaksintaistelu. Pienempi tulos voittaa reiän, ja eniten reikiä voittanut vie ottelun.",
    rules: [
      "Pienempi tulos voittaa reiän. Tasatuloksella reikä puolitetaan eikä ottelutilanne muutu.",
      "Ottelu ratkeaa, kun johto on suurempi kuin jäljellä olevien reikien määrä. Tulos 3&2 tarkoittaa kolmen reiän johtoa, kun kaksi reikää jäi pelaamatta.",
      "Voittaja vie koko sovitun panoksen. Reikiä ei makseta erikseen.",
      "Tasatilanteessa ottelu puolitetaan eikä kumpikaan maksa.",
    ],
    calculation: "Tilanne ilmoitetaan voitettujen reikien erona: 2 up, all square tai esimerkiksi lopputulos 3&2.",
    handicap: "Tasoituksilla nettotuloksia verrataan reikä kerrallaan. Tasoituslyönnit jaetaan tasoitusindeksin mukaan.",
    example: "A voittaa reiät 1 ja 3, reikä 2 puolitetaan. A johtaa kahdella reiällä. Jos A johtaa reiän 16 jälkeen kolmella, ottelu päättyy 3&2.",
    related: ["nassau", "skins", "stableford"],
  },
  {
    key: "skins", slug: "skins", format: "Skins", category: "Klassikot",
    players: "2–4 pelaajaa", order: 2,
    lede: "Jokaisella reiällä on oma potti. Pienimmän tuloksen yksin tehnyt voittaa sen, ja tasapelillä potti siirtyy seuraavalle reiälle.",
    rules: [
      "Jokainen maksaa saman reikäkohtaisen panoksen.",
      "Yksin pienimmän tuloksen tehnyt pelaaja voittaa reiän koko potin.",
      "Jos pienin tulos jaetaan, potti siirtyy seuraavalle reiälle.",
      "Viimeisen reiän jälkeen jäljellä oleva siirtynyt potti jaetaan tasan.",
    ],
    calculation: "Reiän peruspotti on panos kertaa pelaajien määrä. Neljällä pelaajalla ja 5 € panoksella potti on 20 €. Yksi siirto tekee seuraavan reiän potista 40 €.",
    handicap: "Bruttopelissä todelliset lyönnit ratkaisevat. Nettopelissä tasoituslyönnit vähennetään ennen reikäkohtaista vertailua.",
    example: "Neljä pelaajaa pelaa 5 € reiältä. Reikä 1 tasataan, joten 20 € siirtyy. B voittaa reiän 2 yksin ja saa 40 €.",
    related: ["matchspel", "nassau", "stableford"],
  },
  {
    key: "nassau", slug: "nassau", format: "Nassau", category: "Klassikot",
    players: "2–4 pelaajaa", order: 3,
    lede: "Kolme reikäpeliä samalla kierroksella: etuysi, takaysi ja koko 18 reikää. Jokaisella on oma panoksensa.",
    rules: [
      "Etuysi, takaysi ja koko kierros lasketaan erillisinä reikäpeleinä.",
      "Pienin tulos voittaa reiän; tasatuloksella reikä puolitetaan.",
      "Segmentin eniten reikiä voittanut vie sen potin. Tasapelissä panokset palautuvat.",
      "Vähintään kaksi reikää tappiolla oleva voi aloittaa pressin seuraavasta pelaamattomasta reiästä.",
    ],
    calculation: "Kolmen peruspelin tulokset selvitetään erikseen. Myös jokainen pressi on oma minipelinsä samalla sovitulla panoksella.",
    handicap: "Nassau pelataan tavallisesti nettoreikäpelinä, jolloin tasoituslyönnit osuvat tasoitusindeksin mukaisille rei’ille.",
    example: "A voittaa etuysin 5–2, takaysi päättyy 4–4 ja A voittaa koko kierroksen. A saa kahden segmentin voitot, mutta takaysin panos palautuu.",
    related: ["matchspel", "skins", "stableford"],
  },
  {
    key: "stableford", slug: "pistebogey", format: "Pistebogey (Stableford)", category: "Klassikot",
    players: "2–4 pelaajaa", order: 4,
    lede: "Kerää pisteitä nettotuloksesta reikä kerrallaan. Eniten pisteitä saanut voittaa, eikä yksi huono reikä pilaa koko kierrosta.",
    rules: [
      "Nettopar on 2 pistettä, birdie 3, eagle 4 ja albatrossi 5.",
      "Nettobogey on 1 piste. Tuplabogey tai huonompi antaa 0 pistettä.",
      "Eniten pisteitä saanut voittaa potin. Tasapelillä potti jaetaan.",
      "Kun reiältä ei voi enää saada pistettä, pallon voi nostaa ja jatkaa seuraavalle.",
    ],
    calculation: "Pisteet lasketaan reiän nettotuloksesta. 36 pistettä 18 reiällä vastaa omaan tasoitukseen pelaamista.",
    handicap: "Tasoituslyönnit vähennetään bruttotuloksesta tasoitusindeksin mukaan ennen pisteiden laskemista.",
    example: "Pelaaja saa par 4 -reiällä yhden tasoituslyönnin ja tekee bruttobogeyn 5. Nettotulos on par, joten hän saa 2 pistettä.",
    related: ["slaggolf", "quota", "skins"],
  },
  {
    key: "quota", slug: "quota", format: "Quota", category: "Klassikot",
    players: "2–4 pelaajaa", order: 5,
    lede: "Tasoitus määrittää henkilökohtaisen pistetavoitteen. Tavoitteensa eniten ylittänyt voittaa.",
    rules: [
      "Tavoite on 36 miinus pelitasoitus.",
      "Pisteet ovat kuten pistebogeyssa: eagle 4, birdie 3, par 2 ja bogey 1.",
      "Tulos on kerätyt pisteet miinus oma tavoite.",
      "Suurin tavoite-ero voittaa; aikaisin lopetetulla kierroksella tavoite suhteutetaan pelattuihin reikiin.",
    ],
    calculation: "Pelitasoituksella 10 tavoite on 26. Jos pelaaja saa 32 bruttopistettä, Quota-tulos on +6.",
    handicap: "Quota käyttää pelitasoitusta tavoitteen määrittämiseen, joten pisteitä ei lisäksi lasketa nettotuloksesta.",
    example: "A:n tavoite on 26 ja pisteet 32, tulos +6. B:n tavoite on 31 ja pisteet 33, tulos +2. A voittaa.",
    related: ["stableford", "slaggolf", "skins"],
  },
  {
    key: "slaggolf", slug: "lyontipeli", format: "Lyöntipeli", category: "Klassikot",
    players: "2–4 pelaajaa", order: 6,
    lede: "Perinteinen lyöntipeli. Kaikki kierroksen lyönnit lasketaan yhteen, ja pienin kokonaismäärä voittaa.",
    rules: [
      "Jokainen reikä pelataan loppuun ja kaikki lyönnit lasketaan.",
      "Pienimmän kokonaislyöntimäärän tehnyt voittaa potin.",
      "Tasatuloksella potti jaetaan tasan voittajien kesken.",
      "Peli voidaan ratkaista brutto- tai nettotuloksella.",
    ],
    calculation: "Bruttotulos on kaikkien lyöntien summa. Nettotuloksessa kierroksen tasoituslyönnit vähennetään bruttotuloksesta.",
    handicap: "Nettopelissä tasoituslyönnit kohdistetaan reikäkohtaisesti tasoitusindeksin mukaan.",
    example: "A pelaa 82 lyöntiä pelitasoituksella 12 ja saa nettotuloksen 70. B pelaa 78 pelitasoituksella 5 ja saa 73. A voittaa nettopelin.",
    related: ["stableford", "quota", "matchspel"],
  },
  {
    key: "wolf", slug: "wolf", format: "Wolf", category: "Reikäpelit",
    players: "3–4 pelaajaa", order: 1,
    lede: "Jokaisella reiällä yksi pelaaja on Wolf. Hän valitsee parin tai haastaa muut yksin suuremmalla panoksella.",
    rules: [
      "Wolf vuorottelee pelaajajärjestyksessä ja avaa reiällä ensimmäisenä.",
      "Wolf voi valita jonkun seuraavista avaajista parikseen.",
      "Lone Wolf pelaa yksin 2× panoksella kaikkien avausten jälkeen.",
      "Blind Wolf ilmoitetaan ennen ensimmäistä avausta ja pelataan 3× panoksella.",
    ],
    calculation: "Voittava puoli saa 1×, 2× tai 3× panoksen jokaiselta häviäjältä Wolfin valinnan mukaan.",
    handicap: "Joukkueen tulos on sen parempi nettotulos, kun tasoitukset ovat käytössä.",
    example: "10 € yksikköpanoksella Lone Wolf voittaa kolmea pelaajaa vastaan ja saa 20 € jokaiselta, yhteensä 60 €.",
    related: ["split-sixes", "bingo-bango-bongo", "skins"],
  },
  {
    key: "bingo-bango-bongo", slug: "bingo-bango-bongo", format: "Bingo Bango Bongo", category: "Reikäpelit",
    players: "2–4 pelaajaa", order: 2,
    lede: "Jokaisella reiällä jaetaan kolme pistettä: ensin viheriöllä, lähimmäs lippua ja ensin reikään.",
    rules: [
      "Bingo: ensimmäinen pallo viheriöllä.",
      "Bango: lähimpänä lippua, kun kaikki pallot ovat viheriöllä.",
      "Bongo: ensimmäinen pallo reikään.",
      "Pelatkaa oikeassa lyöntijärjestyksessä, jotta pisteet jakautuvat reilusti.",
    ],
    calculation: "Jokaisen pelaajaparin piste-ero kerrotaan panoksella. Näin jokainen pelaa jokaista muuta vastaan.",
    handicap: "Peli ei tarvitse tasoitusta, koska se palkitsee kolmea eri tapahtumaa eikä vain pienintä lyöntimäärää.",
    example: "A saa Bingon ja Bongon, C saa Bangon. Reiän pisteet ovat A 2, C 1 sekä B ja D 0.",
    related: ["wolf", "split-sixes", "narmast-flaggan"],
  },
  {
    key: "split-sixes", slug: "split-sixes", format: "Split Sixes", category: "Reikäpelit",
    players: "3 pelaajaa", order: 3,
    lede: "Kolme pelaajaa jakaa jokaisella reiällä kuusi pistettä tulosten perusteella.",
    rules: [
      "Yksi voittaja saa 4 pistettä, toinen 2 ja viimeinen 0.",
      "Jaettu ykkössija antaa molemmille 3 pistettä ja viimeiselle 0.",
      "Jaettu kakkossija antaa voittajalle 4 ja muille yhden pisteen.",
      "Kaikkien tasatuloksella jokainen saa 2 pistettä.",
    ],
    calculation: "Loppuselvitys tehdään pelaajapareittain: piste-ero kertaa sovittu panos.",
    handicap: "Peli voidaan laskea brutto- tai nettotuloksista. Nettopelissä tasoituslyönnit jaetaan tasoitusindeksin mukaan.",
    example: "A pelaa 3, B 4 ja C 5. A saa 4 pistettä, B 2 ja C 0.",
    related: ["wolf", "bingo-bango-bongo", "skins"],
  },
  {
    key: "klubbroulette", slug: "mailaruletti", format: "Mailaruletti", category: "Reikäpelit",
    players: "2–4 pelaajaa", order: 4,
    lede: "Valituilla rei’illä jokaiselle arvotaan yksi maila, jolla koko reikä pelataan.",
    rules: [
      "Rulettireiät valitaan tai arvotaan ennen kierrosta.",
      "Jokaiselle pelaajalle arvotaan yksi maila tiiltä viheriölle.",
      "Putteria saa käyttää, kun pallo on viheriöllä.",
      "Pienin tulos voittaa reiän; tasatuloksella potti jaetaan.",
    ],
    calculation: "Jokainen rulettireikä on oma kilpailunsa. Voittaja saa sovitun panoksen jokaiselta muulta.",
    handicap: "Mailaruletti voidaan pelata brutto- tai nettotuloksella porukan sopimuksen mukaan.",
    example: "A saa hiekkawedgen, B rautaseiskan ja C draiverin. B tekee pienimmän tuloksen ja voittaa reiän.",
    related: ["wolf", "skins", "golfpoker"],
  },
  {
    key: "scramble", slug: "scramble", format: "Scramble", category: "Joukkuepelit",
    players: "4 pelaajaa, 2 joukkuetta", order: 1,
    lede: "Kaikki joukkueen pelaajat lyövät, paras pallo valitaan ja kaikki jatkavat siitä.",
    rules: [
      "Molemmat joukkueen jäsenet avaavat jokaisella reiällä.",
      "Joukkue valitsee paremman pallon ja molemmat lyövät seuraavan lyönnin samasta paikasta.",
      "Joukkueella on yksi yhteinen reikäkohtainen tulos.",
      "Pienimmän kokonaistuloksen joukkue voittaa.",
    ],
    calculation: "Molemmat voittajajoukkueen pelaajat saavat saman netto-osuuden potista.",
    handicap: "Wager Golf käyttää kahden hengen scramblelle kaavaa 35 % pienemmästä ja 15 % suuremmasta pelitasoituksesta.",
    example: "Joukkue A pelaa 68 ja B 72. Neljä pelaajaa maksaa 20 €, joten 80 € potti jaetaan A:n kahdelle pelaajalle.",
    related: ["foursome", "greensome", "bastboll"],
  },
  {
    key: "foursome", slug: "foursome", format: "Foursome", category: "Joukkuepelit",
    players: "4 pelaajaa, 2 joukkuetta", order: 2,
    lede: "Kahden hengen joukkue pelaa yhtä palloa vuorolyönnein. Avausvuorot sovitaan parittomille ja parillisille rei’ille.",
    rules: [
      "Joukkue pelaa yhdellä yhteisellä pallolla.",
      "Pelaajat lyövät vuorotellen reikään asti.",
      "Toinen avaa parittomat ja toinen parilliset reiät koko kierroksen ajan.",
      "Pienimmän kokonaistuloksen joukkue voittaa.",
    ],
    calculation: "Joukkueet vertaavat kierroksen brutto- tai nettolyöntejä. Voittajat jakavat potin.",
    handicap: "Joukkuetasoitus on 50 % pelaajien yhteenlasketuista pelitasoituksista.",
    example: "Anna avaa, Carl lyö toisen, Anna kolmannen ja Carl puttaa. Joukkueen tulos on neljä lyöntiä.",
    related: ["scramble", "greensome", "bastboll"],
  },
  {
    key: "greensome", slug: "greensome", format: "Greensome", category: "Joukkuepelit",
    players: "4 pelaajaa, 2 joukkuetta", order: 3,
    lede: "Molemmat avaavat, joukkue valitsee paremman avauksen ja jatkaa sen jälkeen vuorolyönnein.",
    rules: [
      "Molemmat joukkueen jäsenet avaavat.",
      "Joukkue valitsee paremman avauksen.",
      "Pelaaja, jonka avausta ei valittu, lyö toisen lyönnin.",
      "Sen jälkeen palloa pelataan vuorotellen reikään asti.",
    ],
    calculation: "Pienimmän brutto- tai nettokokonaistuloksen joukkue voittaa ja jakaa potin.",
    handicap: "Joukkuetasoitus on 60 % pienemmästä ja 40 % suuremmasta pelitasoituksesta.",
    example: "Annan avaus valitaan, joten Carl lyö toisen lyönnin. Anna lyö kolmannen ja vuorottelu jatkuu reikään asti.",
    related: ["foursome", "scramble", "bastboll"],
  },
  {
    key: "bastboll", slug: "four-ball", format: "Four-Ball", category: "Joukkuepelit",
    players: "4 pelaajaa, 2 joukkuetta", order: 4,
    lede: "Kaikki pelaavat omaa palloaan. Joukkueen pienempi tulos lasketaan jokaisella reiällä.",
    rules: [
      "Neljä pelaajaa jaetaan kahteen kahden hengen joukkueeseen.",
      "Jokainen pelaa omaa palloaan koko kierroksen.",
      "Joukkueen tulos on sen kahdesta reikäkohtaisesta tuloksesta pienempi.",
      "Peli voidaan ratkaista reikä- tai lyöntipelinä.",
    ],
    calculation: "Reikäpelissä lasketaan voitetut reiät. Lyöntipelissä joukkueen paremmat reikäkohtaiset tulokset lasketaan yhteen.",
    handicap: "Muut pelaajat saavat 90 % pelitasoitusten erosta pienimmän tasoituksen pelaajaan nähden.",
    example: "Joukkue A:n tulokset ovat 4 ja 5, joten joukkueen tulos on 4. B:n tulokset ovat 3 ja 6, joten B voittaa reiän tuloksella 3.",
    related: ["scramble", "foursome", "vegas"],
  },
  {
    key: "vegas", slug: "vegas", format: "Vegas", category: "Joukkuepelit",
    players: "4 pelaajaa, 2 joukkuetta", order: 5,
    lede: "Joukkueen kaksi tulosta muodostavat kaksinumeroisen luvun. Pienempi luku voittaa, ja erotus määrää reiän arvon.",
    rules: [
      "Pienempi tulos on kymmenluku ja suurempi ykkösluku: 4 ja 6 muodostavat luvun 46.",
      "Vähintään 10 lyönnin tulos kirjoitetaan ensin: 4 ja 10 muodostavat 104.",
      "Birdie voi kääntää vastustajan luvun ja eagle tuplata erotuksen.",
      "Lukujen erotus kerrotaan pistekohtaisella panoksella.",
    ],
    calculation: "Jos joukkueiden luvut ovat 45 ja 46, erotus on yksi. Panoksella 2 €/piste reiän arvo on 2 €.",
    handicap: "Vegas voidaan pelata brutto- tai nettotuloksilla porukan valinnan mukaan.",
    example: "A tekee tulokset 3 ja 4, eli 34. B tekee 5 ja 6, mutta A:n birdie kääntää B:n luvuksi 65. Erotus on 31.",
    related: ["bastboll", "scramble", "wolf"],
  },
  {
    key: "birdiepott", slug: "birdiepotti", format: "Birdiepotti", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 1,
    lede: "Birdieistä maksetaan joko suoraan pelaajien välillä tai yhteisestä kierrospotista.",
    rules: [
      "Birdiekohtaisessa pelissä jokainen muu maksaa birdien tehneelle panoksen.",
      "Pottipelissä kaikki maksavat yhteiseen pottiin ja eniten birdieitä tehnyt voittaa.",
      "Pottipelin tasatuloksella potti jaetaan.",
      "Eagle, albatrossi ja hole-in-one lasketaan yhdeksi birdie-tapahtumaksi.",
    ],
    calculation: "Birdiekohtainen tulos selvitetään pelaajapareittain. Pottipelissä pelaajan netto on saatu osuus miinus oma osallistumispanos.",
    handicap: "Birdiet voidaan laskea bruttona tai nettona. Nettobirdie syntyy tasoituslyönnin vähentämisen jälkeen.",
    example: "A tekee birdien neljän pelaajan ryhmässä 5 € panoksella. B, C ja D maksavat kukin 5 €, joten A saa 15 €.",
    related: ["skins", "sandie", "golfpoker"],
  },
  {
    key: "snake", slug: "snake", format: "Snake", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 2,
    lede: "Jokainen kolmen putin tulos siirtää Snaken ja kasvattaa pottia. Viimeinen Snaken haltija maksaa.",
    rules: [
      "Kolme puttia tehnyt saa Snaken ja kasvattaa pottia yhdellä panoksella.",
      "Seuraava kolmen putin tehnyt ottaa Snaken ja kasvattaa pottia uudelleen.",
      "Kierroksen lopussa Snaken haltija maksaa koko potin.",
      "Jos kolmen putin tuloksia ei tule, kukaan ei maksa.",
    ],
    calculation: "Potti on kolmen putin tapahtumien määrä kertaa panos. Maksu jaetaan tasan muille pelaajille.",
    handicap: "Snake perustuu puttien määrään eikä käytä tasoitusta.",
    example: "Viisi kolmen putin tulosta 3 € panoksella tekee 15 € potin. Viimeinen Snaken haltija maksaa sen muille.",
    related: ["sandie", "birdiepott", "skins"],
  },
  {
    key: "sandie", slug: "sandie", format: "Sandie", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 3,
    lede: "Käy bunkkerissa ja tee silti par tai parempi. Onnistunut pelastus palkitaan.",
    rules: [
      "Bunkkerissa käynyt pelaaja saa sandien tekemällä parin tai paremman.",
      "Jokainen muu pelaaja maksaa sandien tehneelle sovitun panoksen.",
      "Samalla kierroksella voi saada useita sandieita.",
      "Sopikaa ennen kierrosta, lasketaanko vain viheriöbunkkerit vai kaikki bunkkerit.",
    ],
    calculation: "Jokainen sandie on erillinen tapahtuma. Voittaja saa panoksen jokaiselta muulta pelaajalta.",
    handicap: "Sandie lasketaan yleensä bruttotuloksesta, mutta porukka voi valita nettotavan.",
    example: "B käy bunkkerissa ja tekee parin. Kolme muuta maksaa hänelle 5 €, joten B saa 15 €.",
    related: ["birdiepott", "snake", "narmast-flaggan"],
  },
  {
    key: "narmast-flaggan", slug: "lahimmas-lippua", format: "Lähimmäs lippua", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 4,
    lede: "Valitun par 3 -reiän lähimmäs lippua päätynyt avaus voittaa.",
    rules: [
      "Kilpailu valitaan yhdelle tai useammalle par 3 -reiälle.",
      "Pallon on tavallisesti oltava viheriöllä.",
      "Lähimpänä lippua oleva hyväksytty avaus voittaa reiän potin.",
      "Jos kukaan ei osu viheriöön, voittajaa ei ole, ellei paikallissäännöstä ole sovittu.",
    ],
    calculation: "Jokainen valittu reikä on oma kilpailunsa. Voittaja saa panoksen jokaiselta muulta.",
    handicap: "Kilpailu ei käytä tasoitusta, koska vain avauksen etäisyys lipusta ratkaisee.",
    example: "C:n pallo päätyy 3,2 metrin päähän lipusta ja on ryhmän lähin viheriöllä. C voittaa reiän.",
    related: ["langst-drive", "birdiepott", "bingo-bango-bongo"],
  },
  {
    key: "langst-drive", slug: "pisin-draivi", format: "Pisin draivi", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 5,
    lede: "Valitun reiän pisin väylälle päätynyt avaus voittaa.",
    rules: [
      "Kilpailu pelataan yleensä par 4- tai par 5 -reiällä.",
      "Avauksen täytyy päätyä väylälle, ellei muusta ole sovittu.",
      "Pisin hyväksytty avaus voittaa reiän potin.",
      "Jos hyväksyttyä avausta ei ole, voittajaa ei merkitä.",
    ],
    calculation: "Jokainen valittu reikä on oma kilpailunsa. Voittaja saa panoksen jokaiselta muulta.",
    handicap: "Pisin draivi ei käytä tasoitusta.",
    example: "D lyö 265 metrin avauksen keskelle väylää ja voittaa kilpailun. Raffiin päätynyttä pidempää avausta ei lasketa.",
    related: ["narmast-flaggan", "birdiepott", "sandie"],
  },
  {
    key: "golfpoker", slug: "golfpokeri", format: "Golfpokeri", category: "Sivupelit",
    players: "2–4 pelaajaa", order: 6,
    lede: "Ansaitse kortteja pareilla, birdieillä, eagleilla ja hyvillä puteilla. Paras viiden kortin pokerikäsi voittaa.",
    rules: [
      "Par antaa 1 kortin, birdie 2 sekä eagle tai parempi 3 korttia.",
      "Nolla puttia antaa 2 bonuskorttia; yhden putin par tai birdie yhden bonuskortin.",
      "Yhdeltä reiältä voi saada enintään 5 korttia.",
      "Sovellus valitsee kierroksen jälkeen parhaan viiden kortin käden. Alle viidellä kortilla ei voi voittaa.",
    ],
    calculation: "Kaikki maksavat ennen kierrosta yhteiseen pottiin. Paras pokerikäsi voittaa, ja yhtä vahvoilla käsillä potti jaetaan.",
    handicap: "Kortit voidaan ansaita brutto- tai nettotuloksista valitun asetuksen mukaan. Hole-in-one antaa aina vähintään kolme tuloskorttia.",
    example: "Birdie yhdellä putilla antaa kaksi korttia birdiestä ja yhden bonuskortin putista, yhteensä kolme korttia.",
    related: ["birdiepott", "klubbroulette", "skins"],
  },
];

for (const guide of guides) {
  guide.title = `${guide.format} golfissa: säännöt ja laskenta | Wager Golf`;
  guide.description = `${guide.format}: säännöt, pisteiden tai potin laskenta, tasoitus ja käytännön esimerkki.`;
  guide.h1 = `${guide.format} golfissa`;
  guide.faq = [
    {
      q: `Kuinka monelle pelaajalle ${guide.format} sopii?`,
      a: `Pelimuoto sopii määrälle ${guide.players.toLowerCase()}. Tarkista lisäksi säännöistä mahdollinen joukkuejako.`,
    },
    {
      q: `Voiko pelimuotoa ${guide.format} pelata tasoituksilla?`,
      a: guide.handicap,
    },
    {
      q: `Laskeeko Wager Golf pelimuodon ${guide.format} automaattisesti?`,
      a: "Kyllä. Syötä reikäkohtaiset tulokset, niin sovellus näyttää tilanteen suorana ja tekee loppuselvityksen kierroksen jälkeen.",
    },
  ];
}

module.exports = guides;
